{
 "title": "Behavioural Dashboard",
 "tags": [ "overview" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ElementStereotype) (elements{ElementStereotype=~\"activity|activitypartition|action|functionalrequirement\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rule Value History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "ruleValue{RuleType=\"Behaviour\"}",
     "legendFormat": "{{Rule}}"
    }
   ]
  },
  {
   "title": "Model Size History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum by(ElementStereotype) (elements{ElementStereotype=~\"activity|activitypartition|action|functionalrequirement\"})",
     "legendFormat": "{{ElementStereotype}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select t_object.name as 'Rule', t_object.note as 'Rule Detail' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_package.ea_guid = '{B97C11CF-1017-4029-8CF7-A2CB9191BFF7}'\r\norder by t_object.name"
    }
   ]
  },
  {
   "title": "Rule Value History",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ruleValue{RuleType=\"Behaviour\"}",
     "legendFormat": "{{Rule}}"
    }
   ]
  },
  {
   "title": "Elements Failing Rules",
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 10 },
   "targets": [
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select 'R-11' as 'Rule', to2.name as 'Element Name', to2.ea_guid as 'GUID' from t_object to2  \r\nleft join t_connector tc on tc.Start_Object_ID =  to2.Object_ID and tc.Stereotype = 'allocate'\r\nleft join t_object to3 on to3.object_id = tc.End_Object_ID and (to3.stereotype = 'block' or to3.object_type = 'Part')\r\nleft join t_object classifier on classifier.ea_guid = to2.Classifier_guid and classifier.object_type = 'Activity'\r\nleft join t_connector tc2 on tc2.Start_Object_ID =  classifier.Object_ID and tc2.Stereotype = 'allocate'\r\nleft join t_object to4 on to4.object_id = tc2.End_Object_ID and (to4.stereotype = 'block' or to4.object_type = 'Part')\r\nwhere to2.Object_Type in ('Action', 'Activity') and to3.object_id is null and to4.object_id is null\r\nunion all\r\nselect 'R-12' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_object classifier on classifier.Object_ID = t_object.Classifier and classifier.Stereotype = 'block'\r\nwhere t_object.Object_Type  = 'ActivityPartition' and classifier.Object_ID is null\r\nunion all\r\nSelect 'R-13' as 'Rule', action_pin.name as 'Element Name', action_pin.ea_guid as 'GUID'from t_object as action_pin\r\nleft join t_object start_action on start_action.Object_ID = action_pin.ParentID\r\nleft join t_object start_partition on start_partition.Object_ID = start_action.ParentID\r\nleft join t_object start_classifier on start_classifier.object_id = start_partition.classifier\r\nleft join t_connector object_flow on (object_flow.Start_Object_ID = action_pin.Object_ID or object_flow.end_Object_ID = action_pin.Object_ID) and object_flow.Connector_Type = 'ObjectFlow'\r\nleft join t_object end_pin on (object_flow.Start_Object_ID = end_pin.Object_ID or object_flow.end_Object_ID = end_pin.Object_ID) and end_pin.object_type = 'ActionPin'\r\nleft join t_object end_action on end_action.Object_ID = end_pin.ParentID\r\nleft join t_object end_partition on end_partition.Object_ID = end_action.ParentID\r\nleft join t_object end_classifier on end_classifier.object_id = end_partition.classifier\r\nleft join t_connector start_allocate on start_allocate.start_object_id = action_pin.Object_ID and start_allocate.Stereotype = 'allocate'\r\nleft join t_object start_port on start_port.object_id = start_allocate.end_object_id\r\nleft join t_object start_object on start_object.object_id = start_port.parentID\r\nwhere action_pin.object_type = 'ActionPin' and end_partition.object_id <> start_partition.object_id \r\nand IFNULL(start_classifier.object_id,0) <> IFNULL(start_object.object_id,0)\r\nunion all\r\nselect 'R-14' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_connector on t_connector.start_object_id = t_object.object_id\r\nwhere t_object.object_type = 'activity' and t_connector.connector_id is null\r\nunion all\r\nselect 'R-15' as 'Rule', to2.name as 'Element Name', to2.ea_guid as 'GUID' from t_object to2\r\nleft join t_object apartion on apartion.Object_ID =to2.ParentID\r\nleft join t_object partclassifier on partclassifier.Object_ID = apartion.Classifier and partclassifier.Stereotype = 'block'\r\nleft join t_connector tc on tc.Start_Object_ID =  to2.Object_ID and tc.Stereotype = 'allocate'\r\nleft join t_object to3 on to3.object_id = tc.End_Object_ID and (to3.stereotype = 'block' or to3.object_type = 'Part')\r\nleft join t_object classifier on classifier.ea_guid = to2.Classifier_guid and classifier.object_type = 'Activity'\r\nleft join t_connector tc2 on tc2.Start_Object_ID =  classifier.Object_ID and tc2.Stereotype = 'allocate'\r\nleft join t_object to4 on to4.object_id = tc2.End_Object_ID and (to4.stereotype = 'block' or to4.object_type = 'Part')\r\nleft join t_object to45 on to45.ea_guid = to4.PDATA1 and to45.Stereotype = 'block'\r\nleft join t_object to5 on to5.ea_guid = to3.PDATA1 and to5.Stereotype = 'block'\r\nwhere to2.Object_Type = 'Action' and partclassifier.object_id <> IFNULL(to3.object_id,0) and partclassifier.object_id <> IFNULL(to4.object_id,0) and partclassifier.object_id <> IFNULL(to5.object_id,0) and partclassifier.object_id <> IFNULL(to45.object_id,0)\r\n"
    }
   ]
  }
 ]
}