{
 "title": "Project Overview",
 "tags": [ "overview" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Hybrid SUV Project\n\nThis project demonstrates the design for the Hybrid SUV.\n\n"
   }
  },
  {
   "title": "Model Elements",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Supertype) (label_replace(label_replace(label_replace(label_replace(label_replace(elements, \"Supertype\", \"Structural\", \"ElementStereotype\", \"(block|interfaceblock|proxyconnector|proxyport|signal|part|port)\"), \"Supertype\", \"Behaviour\", \"ElementStereotype\", \"(action|actionpin|activity|mergenode|activityparameter|activitypartition|centralbuffernode|interruptibleactivityregion)\"), \"Supertype\", \"Use Case\", \"ElementStereotype\", \"(actor|usecase)\"), \"Supertype\", \"Misc\", \"ElementStereotype\", \"(boundary|note|package|statenode|synchronization)\"), \"Supertype\", \"Requirements\", \"ElementStereotype\", \"(requirement|functionalrequirement|extendedrequirement)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Errors",
   "type": "gauge",
   "description": "This panel shows the number of rule violations that are currently present in the model.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(RuleType) (ruleValue)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model Elements",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(Supertype) (label_replace(label_replace(label_replace(label_replace(label_replace(elements, \"Supertype\", \"Structural\", \"ElementStereotype\", \"(block|interfaceblock|proxyconnector|proxyport|signal|part|port)\"), \"Supertype\", \"Behaviour\", \"ElementStereotype\", \"(action|actionpin|activity|mergenode|activityparameter|activitypartition|centralbuffernode|interruptibleactivityregion)\"), \"Supertype\", \"Use Case\", \"ElementStereotype\", \"(actor|usecase)\"), \"Supertype\", \"Misc\", \"ElementStereotype\", \"(boundary|note|package|statenode|synchronization)\"), \"Supertype\", \"Requirements\", \"ElementStereotype\", \"(requirement|functionalrequirement|extendedrequirement)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Elements",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Supertype) (label_replace(label_replace(label_replace(label_replace(label_replace(elements, \"Supertype\", \"Structural\", \"ElementStereotype\", \"(block|interfaceblock|proxyconnector|proxyport|signal|part|port)\"), \"Supertype\", \"Behaviour\", \"ElementStereotype\", \"(action|actionpin|activity|mergenode|activityparameter|activitypartition|centralbuffernode|interruptibleactivityregion)\"), \"Supertype\", \"Use Case\", \"ElementStereotype\", \"(actor|usecase)\"), \"Supertype\", \"Misc\", \"ElementStereotype\", \"(boundary|note|package|statenode|synchronization)\"), \"Supertype\", \"Requirements\", \"ElementStereotype\", \"(requirement|functionalrequirement|extendedrequirement)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rule Violations by Type",
   "type": "timeseries",
   "description": "This dashboard summarises the total number of violated model rules, grouped by type.",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 10 },
   "targets": [
    { "expr": "sum by(RuleType) (ruleValue)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model Size (By Author)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum by(Author) (elements)", "legendFormat": "__auto" }
   ]
  }
 ]
}