{
 "title": "Requirements Dashboard",
 "tags": [ "overview" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ElementStereotype) (elements{ElementStereotype=~\"functionalrequirement|extendedrequirement\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rule Value History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "ruleValue{RuleType=\"Requirement\"}",
     "legendFormat": "{{Rule}}"
    }
   ]
  },
  {
   "title": "Model Size History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum by(ElementStereotype) (elements{ElementStereotype=~\"functionalrequirement|extendedrequirement\"})",
     "legendFormat": "{{ElementStereotype}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select t_object.name as 'Rule', t_object.note as 'Rule Detail' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_package.ea_guid = '{9666A304-E3CF-45aa-B8D8-B797551EDB19}'"
    }
   ]
  },
  {
   "title": "Rule Value History",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ruleValue{RuleType=\"Requirement\"}",
     "legendFormat": "{{Rule}}"
    }
   ]
  },
  {
   "title": "Elements Failing Rules",
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 10 },
   "targets": [
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select 'R-16' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_connector on t_connector.End_Object_ID = t_object.Object_ID \r\nleft join t_object satisfiedBy on satisfiedBy.Object_ID = t_connector.Start_Object_ID \r\nand satisfiedBy.Object_Type in ('activity','action')\r\nwhere t_object.stereotype = 'FunctionalRequirement' and satisfiedBy.Object_ID is null \r\nunion all\r\nselect 'R-17' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_connector on t_connector.End_Object_ID = t_object.Object_ID \r\nleft join t_object satisfiedBy on satisfiedBy.Object_ID = t_connector.Start_Object_ID \r\nand (satisfiedBy.Stereotype in ('block', 'interfaceblock', 'proxyport') \r\nor satisfiedBy.Object_Type in ('Part','Signal'))\r\nwhere t_object.stereotype = 'ExtendedRequirement' and satisfiedBy.Object_ID is null \r\nunion all\r\nSelect 'R-18' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_connector on t_connector.Start_Object_ID = t_object.Object_ID and (t_connector.Stereotype='deriveReqt' or t_connector.connector_type='Nesting')\r\nwhere t_object.object_type = 'Requirement' and t_connector.connector_id is null\r\nunion all\r\nSelect 'R-19' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_objectproperties on t_objectproperties.Object_ID =t_object.Object_ID and t_objectproperties.Property ='verifyMethod'\r\nwhere t_objectproperties.value is null and t_object.Object_Type ='Requirement'\r\nunion all\r\nSelect 'R-20' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nwhere t_object.Object_Type ='Requirement' and not REGEXP_LIKE(t_object.name, 'SR-FR-\\\\d{3}|SR-NFR-\\\\d{3}') \r\n\r\n"
    }
   ]
  }
 ]
}