{
 "title": "Structural Dashboard",
 "tags": [ "overview" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "EA_MBSE",
     "rawSql": "select count(t_object.object_id) as 'Blocks' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_object.object_type = 'class' and t_object.stereotype = 'block'"
    },
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select count(t_object.object_id) as 'Parts' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_object.object_type = 'part'"
    },
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select count(t_object.object_id) as 'Interface Blocks' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_object.object_type = 'class' and t_object.stereotype = 'interfaceBlock'"
    },
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select count(t_object.object_id) as 'Signals' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_object.object_type = 'signal'"
    },
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select count(t_object.object_id) as 'Ports' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_object.object_type = 'port'"
    }
   ]
  },
  {
   "title": "Rule Value History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "ruleValue{RuleType=\"Structure\"}",
     "legendFormat": "{{Rule}}"
    }
   ]
  },
  {
   "title": "Model Size History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum by(ElementStereotype) (elements{ElementStereotype=~\"block|interfaceblock|part|signal|proxyport\"})",
     "legendFormat": "{{ElementStereotype}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select t_object.name as 'Rule', t_object.note as 'Rule Detail' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_package.ea_guid = '{BC87F8B5-A6F9-4721-82F4-0AF16EF2E949}'\r\norder by t_object.name"
    }
   ]
  },
  {
   "title": "Rule Value History",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ruleValue{RuleType=\"Structure\"}",
     "legendFormat": "{{Rule}}"
    }
   ]
  },
  {
   "title": "Elements Failing Rules",
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 10 },
   "targets": [
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select 'R-06' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_connector on t_connector.start_object_id = t_object.object_id\r\nwhere t_object.object_type = 'class' and t_object.stereotype = 'block' and t_connector.connector_id is null\r\nunion all\r\nselect 'R-07' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_object parent on parent.Object_ID = t_object.ParentID\r\nwhere t_object.Object_Type = 'Port' and t_object.Stereotype is null and parent.Stereotype = 'block'\r\nunion all\r\nselect 'R-08' as 'Rule', t_connector.name as 'Element Name', t_connector.ea_guid as 'GUID' from t_connector\r\ninner join t_object on t_object.Object_ID = t_connector.Start_Object_ID and t_object.Stereotype ='block'\r\nwhere t_connector.Connector_Type ='Aggregation' and t_connector.SourceRole is null\r\nunion all\r\nselect 'R-09' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_object parent on parent.Object_ID  = t_object.ParentID\r\nwhere t_object.Object_Type ='Part' and parent.Stereotype ='block' and t_object.name is null"
    }
   ]
  }
 ]
}