{
 "title": "Use Case Dashboard",
 "tags": [ "overview" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select count(t_object.object_id) as 'Use Cases' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_object.object_type = 'UseCase'\r\n"
    },
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select count(t_object.object_id) as 'Actors' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_object.object_type = 'Actor'"
    }
   ]
  },
  {
   "title": "Rule Value History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "ruleValue{RuleType=\"UseCase\"}",
     "legendFormat": "{{Rule}}"
    }
   ]
  },
  {
   "title": "Model Size History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "Actors", "legendFormat": "{{__name__}}" },
    { "expr": "UseCases", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select t_object.name as 'Rule', t_object.note as 'Rule Detail' from t_object\r\nleft join t_package on t_package.package_id = t_object.package_id\r\nwhere t_package.ea_guid = '{B127F7E6-A7AB-42cd-B364-05167C3F5832}'\r\norder by t_object.name"
    }
   ]
  },
  {
   "title": "Rule Value History",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ruleValue{RuleType=\"UseCase\"}",
     "legendFormat": "{{Rule}}"
    }
   ]
  },
  {
   "title": "Elements Failing Rules",
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 10 },
   "targets": [
    {
     "dataset": "EA_MBSE2",
     "rawSql": "select 'R-01' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_connector on t_connector.start_object_id = t_object.object_id or t_connector.end_object_id = t_object.object_id\r\nwhere t_object.object_type = 'UseCase' and t_connector.connector_id is null\r\nunion all\r\nselect 'R-02' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_connector on t_connector.start_object_id = t_object.object_id or t_connector.end_object_id = t_object.object_id\r\nwhere t_object.object_type = 'Actor' and t_connector.connector_id is null\r\nunion all\r\nselect 'R-03' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_diagramobjects on t_diagramobjects.object_id = t_object.object_id\r\nwhere t_object.object_type = 'Actor' and t_diagramobjects.Diagram_ID is null\r\nunion all\r\nselect 'R-04' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_diagramobjects on t_diagramobjects.object_id = t_object.object_id\r\nwhere t_object.object_type = 'UseCase' and t_diagramobjects.Diagram_ID is null\r\nunion all\r\nselect 'R-05' as 'Rule', t_object.name as 'Element Name', t_object.ea_guid as 'GUID' from t_object\r\nleft join t_xref on t_xref.Client = t_object.ea_guid\r\nleft join t_diagram on t_diagram.ea_guid = t_xref.Supplier \r\nwhere t_diagram.Diagram_ID is null and t_object.Object_Type = 'UseCase'"
    }
   ]
  }
 ]
}